[tool.poetry]
name = "sysdiagnose"
version = "0.1.0"
description = ""
authors = ["Robert Elwell <robert.elwell@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
